In [1]:
import numpy as np

In [21]:
x = [[[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3]]]


In [22]:
x

[[[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]]

In [23]:
y = np.array(x)

In [24]:
y

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [25]:
x =[1,2,3,4,5]


In [26]:
y=[[1,2,3],[4,5,6],[7,8,9]]

In [27]:
np.array(y)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
y


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [30]:
np.array(x)

array([1, 2, 3, 4, 5])

In [35]:
np.zeros((3,2)) + 6

array([[6., 6.],
       [6., 6.],
       [6., 6.]])

In [38]:


np.ones(3)

array([1., 1., 1.])

In [40]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
#unity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
x =[1,2,3,4,5]
y=[[1,2,3],[4,5,6],[7,8,9]]

In [45]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [46]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [48]:
np.arange(50).reshape(5,10) #5 rows 10 col

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [53]:
np.linspace(5,100,5) #start diffrence number of elements

array([  5.  ,  28.75,  52.5 ,  76.25, 100.  ])

In [54]:
x = np.array(x)

In [57]:
x.max()

5

In [58]:
x.min()

1

In [61]:
np.random.rand(5)

array([0.79105202, 0.41877729, 0.89503465, 0.29603151, 0.48406871])

In [62]:
np.random.randn(5)

array([-0.17365365, -0.27648183, -1.76139458,  0.20836034, -0.25345676])

In [66]:
np.random.randint(1,100)

22

In [68]:
x

array([1, 2, 3, 4, 5])

x

In [69]:
x.argmax()

4

In [70]:
x.argmin()

0

In [72]:
x = np.arange(1,21)

In [73]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [74]:
x[8]

9

In [75]:
x[-1]

20

In [78]:
x[: 9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
x[8:]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [80]:
x[-10:-1]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [81]:
y = x[5:15] = 40

In [82]:
y

40

In [83]:
x

array([ 1,  2,  3,  4,  5, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 16, 17,
       18, 19, 20])

In [86]:
y = x.copy()

In [87]:
y

array([ 1,  2,  3,  4,  5, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 16, 17,
       18, 19, 20])

In [88]:
y[5:15] = 80

In [89]:
y

array([ 1,  2,  3,  4,  5, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 16, 17,
       18, 19, 20])

In [90]:
x = np.arange(25).reshape(5,5)

In [91]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [92]:
x[2][2]

12

In [93]:
x[2,2]

12

In [95]:
#slice 2d 

x[0:2,2:]

array([[2, 3, 4],
       [7, 8, 9]])

In [96]:
x[1:4,1:4] #[ROW:ROW,COL:COL]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [97]:
y 

array([ 1,  2,  3,  4,  5, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 16, 17,
       18, 19, 20])

In [98]:
y = np.arange(1,20)

In [99]:
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [100]:
y > 12

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [102]:
y[y > 12]

array([13, 14, 15, 16, 17, 18, 19])

In [103]:
y[y % 12]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,  6,
        7,  8])

In [104]:
x = np.arange(10)

In [105]:
y = np.arange(10,20)

In [106]:
z = x + y

In [107]:
z

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [108]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [111]:
np.cos(x)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [112]:
np.log(x)

C:\Users\LENOVO\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [113]:
np.max(x)

9

In [119]:
x = np.arange(12).reshape(4,3)

In [121]:
y = np.arange(10,22).reshape(4,3)

In [122]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [123]:
y

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [124]:
z = x*y

In [125]:
z

array([[  0,  11,  24],
       [ 39,  56,  75],
       [ 96, 119, 144],
       [171, 200, 231]])

In [126]:
x =np.arange(20)

In [127]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [128]:
x.sum()

190

In [129]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

x = arr[arr%2==1]

print(x)

[1 3 5 7 9]
